### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by jechaviz** [dorkbox/Notify#1]
Just to be capable to select the fontType, fontSize and fontWeight for both title and body message.

Thank you.

**Comment by dorkbox** [comment]
You actually can :)  -- I had forgotten to add this info to the documentation, so thanks for reminding me!

Just specify 
`NotifyPopup.TITLE_TEXT_FONT`  or `NotifyPopup.MAIN_TEXT_FONT`  to change the font used for those.

And example is `Source Code Pro BOLD 16`.

**Comment by dorkbox** [comment]
Another option I forgot to mention is (I will make it non-final in the next release):

`  /** How long we want it to take for the popups to relocate when one is closed */`
`     public static final float MOVE_DURATION = 1.0F;`

**Comment by dorkbox** [comment]
Version `2.14` has the final modifier removed + updated documentation
