### ISSUE TITLE
Dynamic height

### ISSUE THREAD

**Issue by eljavatar** [dorkbox/Notify#10]
Hi. The truth seems to me very complete the way in which notification messages work.

However, I would like to know if there is any way that the height is dynamic according to the text, that is, that it does not cut it and give it an ellipsis, but that it adapts to the text size in height

Thank you

**Comment by TroniPM** [comment]
Something about it??

**Comment by dorkbox** [comment]
It's possible to have it dynamic -- i just haven't had the time yet

**Comment by TroniPM** [comment]
How so?

**Comment by dorkbox** [comment]
to set the height, you have to measure the size of the text relative to the size of the window, and then change the height as necessary.

**Comment by TroniPM** [comment]
What methods should I use? After `Notify.create()` I couldn't find anything with that purpose.

**Comment by dorkbox** [comment]
No idea... I'd have to look it up, measuring fonts is a java swing thing. this is also something that would have to be added to the library -- not something that could be added on.

**Comment by dorkbox** [comment]
I’ve added support for customizing the size of the notification window.
