### ISSUE TITLE
First notification is stuck under other notifications

### ISSUE THREAD

**Issue by szerencl** [dorkbox/Notify#19]
The first notification is on top of the taskbar (I suspect this could be connected to the issue)
![kép](https://user-images.githubusercontent.com/57007996/99553108-0f2c0400-29be-11eb-96a7-7a6c304037a3.png)

Other notifications float up higher to an ideal height after ~~the first~~ any notification disappears.
![kép](https://user-images.githubusercontent.com/57007996/99552635-844b0980-29bd-11eb-82bf-88563bde5879.png)
Only happens when using Pos.BOTTOM
Using Windows 10 and JDK 8
The problem is happening with version 3.5 and onward

**Comment by szerencl** [comment]
The changes proposed in #20 fix the issue

**Comment by dorkbox** [comment]
This is fixed.
