### ISSUE TITLE
Unable to use Notify and SystemTray in the same application

### ISSUE THREAD

**Issue by Elvander** [dorkbox/Notify#21]
I have an javaFX (java 11) application which needs to send notifications to the user and stay in the tray, but i'm unable to combine both libraries. 

I receive the following error:

`
java.lang.module.ResolutionException: Modules SystemTray and Notify export package dorkbox.util to module hamcrest.core
`

Is there a way to build both packages without the `dorkbox.util` and add this as a dependency? This should resolve the issue...

**Comment by dorkbox** [comment]
This is in progress, and a new release will be "soon". There's a lot of work in the support libraries for this project to fully work with JPMS.

**Comment by basix86** [comment]
Hi. When is planned the new release?

**Comment by dorkbox** [comment]
This is now fixed. SystemTray and Notify are both JPMS compatible.
