### ISSUE TITLE
Resources not present in maven artifact

### ISSUE THREAD

**Issue by dyorgio** [dorkbox/Notify#5]
Hello @dorkbox !

Nice lib :) 👍 .

Trying to use it with maven and this error happens:

```
[LocationResolver] SEARCHING: "resources/dialog-warning.png"
[LocationResolver] FAILED: failed to find anything like
[LocationResolver]                "resources/dialog-warning.png"
```

Looking at artifact, there is no package "resources" inside last jar (3.2).
Maybe a build problem :)

**Comment by dorkbox** [comment]
yup. working on it!

**Comment by dorkbox** [comment]
Added resources + pushed maven artifact.
