### ISSUE TITLE
Implement auto-resize for Notify.graphic

### ISSUE THREAD

**Issue by dyorgio** [dorkbox/Notify#6]
Hello, 

I tried to use a icon with 144x144 with Notify as graphic:
```java
Notify.graphic(img);
```

I expected an auto-resize, because I didn't know that 48px was the correct size.

How about make a auto-resize like SystemTray lib (with cache maybe).

Currently I'm using this working around:
```java
img.getScaledInstance(48, 48, Image.SCALE_SMOOTH)
```

**Comment by dorkbox** [comment]
good idea!

**Comment by dorkbox** [comment]
Now there is resizing. It's not tested, but it should work as intended.

**Comment by dyorgio** [comment]
Hello, version 3.4 is given me this error:

```
java.lang.NoSuchMethodError: dorkbox.util.ImageUtil.resizeImage(Ljava/awt/image/BufferedImage;II)Ljava/awt/image/BufferedImage;
	at dorkbox.notify.Notify.image(Notify.java:245)
```

**Comment by dorkbox** [comment]
I was hoping to avoid having to build a standalone test app.. I'll fix it.

**Comment by dyorgio** [comment]
Sorry @dorkbox, my fault, this happen because I'm using a old version of Systray lib (with same ImageUtil class inside), I updated my version to 3.5 and error stops.
How about isolate this on another maven artifact?

**Comment by dyorgio** [comment]
Resize logic is wrong :P:

I'm trying with a 144x144 image, and this is result:

<img width="330" alt="captura de tela 2017-09-15 as 10 23 53" src="https://user-images.githubusercontent.com/1438251/30484340-7a440748-9a00-11e7-84b4-34f59b857898.png">

The problem is on line 57 of ImageUtil:
```java
// don't use new height on calculation
width = (int) (originalWidth * ratio);
```

**Comment by dorkbox** [comment]
Lol. I'll make the test app, so I can properly test it.

**Comment by dorkbox** [comment]
Fixed.
