### ISSUE TITLE
Click event stops to work on 3.4 (on notify and close button).

### ISSUE THREAD

**Issue by dyorgio** [dorkbox/Notify#7]
Click event stops to work on 3.4 (on notify and close button).
I can't see the diference comparing repository and source.jar :(.

Tested on macOs (returning to 3.2 solves).

**Comment by dorkbox** [comment]
I added the ability to have notifications for applications (previously it was just the desktop), and broke it.

Thanks for reporting!

**Comment by dorkbox** [comment]
Fixed.
